apps/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
   path('login/' , views.login_view , name='login'),
   path('logout/' , views.logout_view , name='logout'),
   path('signup/' , views.signup , name='signup'),
   # path('profile/' , views.profile , name='profile'),
   path('profile/<uuid:id>/' , views.profile , name='profile'),
]

apps/skins/urls.py
from django.urls import path

from . import views

app_name = 'skins'

urlpatterns = [
   path('' , views.index , name='index'),
   path('create/' , views.create , name='create'),
   path('<id>/' , views.detail , name='detail'),
   path('<uuid:id>/like/' , views.like , name='add_like'),
]

coremine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('skins/', include('apps.skins.urls')),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/members/models.py
from uuid import uuid4


from django.db import models
from django.contrib.auth.models import User
# from apps.skins.models import Skin

# Create your models here.
class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    skin = models.ForeignKey('skins.Skin', on_delete=models.SET_NULL, null=True, blank=True)
    likes_skins = models.ManyToManyField('skins.Skin', related_name='liked_by', blank=True)
    
    def __str__(self):
        return self.user.username
    
    
        
    def get_head(self):
        if self.skin:
            return self.skin.get_head()
        return "/media/skins/default_head.png"

apps/members/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Profile

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, 'Welcome back!')
            return redirect('members:profile', id=user.profile.id)
    else:
        form = AuthenticationForm()
    return render(request, 'members/login.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    messages.info(request, 'You have been logged out.')
    return redirect('main:index')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = Profile(user=user)
            profile.save()
            login(request, user)
            messages.success(request, f'Welcome, to the club, {user.username}!')
            messages.add_message(request, messages.INFO, 'You have been registered successfully!')
            return redirect('members:profile', id=profile.id)
    form = UserCreationForm()
    return render(request, 'members/signup.html', {'form': form})

@login_required
def profile(request, id):
    profile = get_object_or_404(Profile, id=id)
    context = {
        'profile': profile
    }
    return render(request, 'members/profile.html', context)

apps/members/templates/members/login.html
{% extends "base.html" %}

{% load static %}


{% block title %}LOGIn page{% endblock %}

{% block content %}
<div class="mt-4 p-4 bg-body-tertiary rounded-lg">
  <h1 class="text-3xl text-center font-bold">
    LOGIn page
  </h1>
</div>
<div class="mt-4 p-4 bg-body-tertiary rounded-lg">
  
  <form method="post">
    {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                <input type="{{ field.field.widget.input_type }}" class="form-control {% if field.errors %}is-invalid{% endif %}" id="{{ field.id_for_label }}" name="{{ field.html_name }}" required>
                {% if field.help_text %}
                    <small id="{{ field.id_for_label }}_help" class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
    <button type="submit" class="btn btn-primary">Увійти</button>
</form>
    <p class="mt-3">Don't have an account? <a href="{% url 'members:signup' %}" class="link-primary">Signup</a></p>
</div>

{% endblock %}

apps/members/templates/members/profile.html
{% extends "base.html" %}

{% load static %}


{% block title %}Profile page{% endblock %}

{% block content %}
<div class="mt-4 p-4 ">
  <h1 class="text-3xl text-center font-bold">
    Profile page
  </h1>
</div>
<div class="mt-4 ">
  <div class="row">
    <div class="col-4">
      <canvas id="canvas" class="skin-3d drop-shadow auto-size align-top mx-auto border" width="330" height="440" style="cursor:move;width:300px" data-id="d2434428eb6a0774" data-model="slim" data-theta="75" data-phi="22"></canvas>
    </div>
    <div class="col">

      <div class="card" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{ profile.get_head}}" class="img-fluid rounded-start">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <p class="card-text">Username: {{ profile.user.username }}</p>
              <p class="card-text">Email: {{ profile.user.email }}</p>
              <p class="card-text">Created: {{ profile.user.date_joined|date:"F d, Y" }}</p>
              <div class="avatar-group">
                {% for skin in profile.likes_skins.all %}
                <a href="{% url 'skins:add_like' skin.id %}">
                  <img class="avatar rounded-0" src="{{skin.get_head}}" alt="{{skin.name}}">
                </a>
                {% endfor %}
              </div>
            </div>
            </div>
            <div class="card-footer">
              <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addSkin">Add skin</a>
            </div>
              
               
              </form>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
  

</div>



<!-- Modal -->
<div class="modal modal-sm fade" id="addSkin" tabindex="-1" aria-labelledby="addSkinLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addSkinLabel">Add Skin</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body p-4">
        <form action="{% url 'skins:create' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name">
          </div>
          <div class="mb-3">
            <label for="image" class="form-label">Image</label>
            <input type="file" class="form-control" id="image" name="image">
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
          </form>
        
      </div>
    </div>
  </div>
</div>



<script src="{% static 'js/skinview3d.bundle.js' %}"></script>
<script>
  const element = document.getElementById("canvas");
  console.log(element);

  const skinViewer = new skinview3d.SkinViewer({
        canvas: element,
        width: 330,
        height: 440,
        skin:"{{profile.skin.image.url}}",
        enableControls: true,
    }); 
    skinViewer.animation = new skinview3d.WalkingAnimation();
    skinViewer.animation.paused = false;
    skinViewer.animation.progress = 3;
    skinViewer.animation.headBobbing = false;
        
    skinViewer.camera.rotation.x = -0.5034319968693;
    skinViewer.camera.rotation.y = -0.36908259614;
    skinViewer.camera.rotation.z = -0.196140179771;
    skinViewer.camera.position.x = -14.993128783689523;
    skinViewer.camera.position.y = 18.699720219168;
    skinViewer.camera.position.z = 33.952134734071;
    skinViewer.controls.enableZoom = false;
   

    //run 2s after the page loads
    setTimeout(() => {
      skinViewer.animation.paused = true;
    }, 10);
    

    function playAnimation() {
      skinViewer.animation.paused = !skinViewer.animation.paused;
      const btn = document.getElementById("play-pause-btn");
      if (skinViewer.animation.paused) {
        btn.innerHTML = '<i class="fas fa-play"></i>';
        btn.title = "Play";
      } else {
        btn.innerHTML = '<i class="fas fa-pause"></i>';
        btn.title = "Pause";
      }
    }

    
    function downloadBase64Image(base64String, filename) {
      // Розбиваємо base64-рядок на дві частини: тип медіа та дані
      const parts = base64String.split(';base64,');
      const mimeType = parts[0].split(':')[1];
      const imageData = atob(parts[1]);
      const bytes = new Uint8Array(imageData.length);
    
        for (let i = 0; i < imageData.length; i++) {
            bytes[i] = imageData.charCodeAt(i);
        }
    
        const blob = new Blob([bytes], { type: mimeType });
  
      if (window.navigator && window.navigator.msSaveOrOpenBlob) {
          // Для Internet Explorer
          window.navigator.msSaveOrOpenBlob(blob, filename);
      } else {
          // Створюємо посилання для завантаження файлу
          const link = document.createElement('a');
          link.href = window.URL.createObjectURL(blob);
          link.download = filename;
  
          // Додаємо посилання у DOM, клікаємо на нього та видаляємо
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
      }
  }


    function capture() {
      const img = skinViewer.canvas.toDataURL("image/png");
      console.log(img);
      downloadBase64Image(img, "skin.png");
    }


</script>
{% endblock %}

apps/members/templates/members/signup.html
{% extends "base.html" %}

{% load static %}


{% block title %}Signup page{% endblock %}

{% block content %}
<div class="mt-4 p-4 bg-body-tertiary rounded-lg">
  <h1 class="text-3xl text-center font-bold">
    Signup page
  </h1>
</div>
<div class="mt-4 p-4 bg-body-tertiary rounded-lg">
  
    <form method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                <input type="{{ field.field.widget.input_type }}" class="form-control {% if field.errors %}is-invalid{% endif %}" id="{{ field.id_for_label }}" name="{{ field.html_name }}" required>
                {% if field.help_text %}
                    <small id="{{ field.id_for_label }}_help" class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}




        <!-- <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="mb-3">
            <label for="password1" class="form-label">Password</label>
            <input type="password" class="form-control" id="password1" name="password1" required>
        </div>
        <div class="mb-3">
            <label for="password2" class="form-label">Password confirmation</label>
            <input type="password" class="form-control" id="password2" name="password2" required>
        </div> -->
        <button type="submit" class="btn btn-primary">Signup</button>
    </form>
    <p class="mt-3">Already have an account? <a href="{% url 'members:login' %}">Login</a></p>
</div>

{% endblock %}