apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
   path('' , views.index , name='index'),
   path('contact_form/' , views.contact_form , name='question')
]

apps/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
   path('login/' , views.login_view , name='login'),
   path('logout/' , views.logout_view , name='logout'),
   path('signup/' , views.signup , name='signup'),
   # path('profile/' , views.profile , name='profile'),
   path('profile/<uuid:id>/' , views.profile , name='profile'),
]

apps/skins/urls.py
from django.urls import path

from . import views

app_name = 'skins'

urlpatterns = [
   path('' , views.index , name='index'),
   path('create/' , views.create , name='create'),
   path('<id>/' , views.detail , name='detail'),
   path('<uuid:id>/like/' , views.like , name='add_like'),
]

coremine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('skins/', include('apps.skins.urls')),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blocks/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
      <a class="navbar-brand flex items-center" href='{% url "main:index" %}'>
        <img src="{% static 'img/logo.svg' %}" alt="logo" width="30" height="30">
        <span class="bold ml-3">Skiner</span>
    </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarPillsExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
    <div class="collapse navbar-collapse" id="navbarPillsExample">
      <ul class="navbar-nav navbar-nav-underline">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'skins:index' %}">Skins</a>
        </li>
      </ul>
    </div>
        
        

        
        <div class="flex gap-2">
          {% if user.is_authenticated %}
          <div class="dropdown align-items-center flex items-center">
            <a href="#" class="link-body-emphasis text-decoration-none dropdown-toggle flex items-center" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
              
              <img src="{{user.profile.get_head}}" alt="mdo" width="32" height="32" class="flex-shrink-0 me-2">
              {{user.username}}
            </a>
            <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
              <li><a class="dropdown-item" href="{% url 'members:profile' user.profile.id %}"><i class="fa-solid fa-user"></i> Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'members:logout' %}"><i class="fa-solid fa-sign-out"></i> Sign out</a></li>
            </ul>
          </div>
          {% else %}
            <a href="{% url 'members:login' %}" class="btn btn-outline-light btn-sm"><i class="fa-solid fa-right-to-bracket"></i> Login</a>
          {% endif %}
        </div>
    </div>
  </nav>