apps/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
   path('login/' , views.login_view , name='login'),
   path('logout/' , views.logout_view , name='logout'),
   path('signup/' , views.signup , name='signup'),
   # path('profile/' , views.profile , name='profile'),
   path('profile/<uuid:id>/' , views.profile , name='profile'),
]

apps/skins/urls.py
from django.urls import path

from . import views

app_name = 'skins'

urlpatterns = [
   path('' , views.index , name='index'),
   path('create/' , views.create , name='create'),
   path('<id>/' , views.detail , name='detail'),
   path('<uuid:id>/like/' , views.like , name='add_like'),
]

coremine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('skins/', include('apps.skins.urls')),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/skins/models.py
import os

from uuid import uuid4
from PIL import Image

from django.db import models

from apps.members.models import Profile

# Create your models here.

def skin_image_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{instance.id}.{ext}"
    return os.path.join('skins/images', filename)

class Skin(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=skin_image_filename)
    image_head = models.ImageField(upload_to='skins/images/head/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='skins', null=True, default=None)

    tags = models.ManyToManyField(
    to='skins.Tag',
    through='skins.SkinTag',
    related_name='skins',
    blank=True,
    )
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Skin'
        verbose_name_plural = 'Skins'
        ordering = ['-created_at']
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.image_head:  # Проверяем, не существует ли уже головы для этого скина
            self.create_head()
            super().save(*args, **kwargs)
    
    def create_head(self):
        img = Image.open(self.image.path).convert("RGBA")
        x, y = img.size
        standard_size = [(8, 8, 16, 16), (40, 8, 48, 16), 128]
        head_coord = [i * (x // 64) for i in standard_size[0]]
        helm_coord = [i * (x // 64) for i in standard_size[1]]
        
        head = img.crop(head_coord)
        helm = img.crop(helm_coord)
        k = standard_size[2] // (x // 64)
        
        x, y = head.size
        head.paste(helm, (0, 0, x, y), helm)
        
        new_width = x * k
        new_height = y * k
        resized_head = head.resize((new_width, new_height), Image.NEAREST)
        
        # Получаем путь для сохранения
        head_filename = os.path.join('skins/images/head/', f"{self.id}.png")
        if not os.path.exists('media/skins/images/head/'):
            os.makedirs('media/skins/images/head/')
        resized_head.save(f"media/{head_filename}")
        
        # Присваиваем значение полю image_head
        self.image_head.name = head_filename
        
    def get_head(self):
        if not self.image_head:
            self.create_head()
            self.save()
        return self.image_head.url
    
class SkinTag(models.Model):
    skin = models.ForeignKey(Skin, on_delete=models.CASCADE)
    tag = models.ForeignKey('skins.Tag', on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.skin.name} - {self.tag.name}"
    
    class Meta:
        verbose_name = 'Skin-Tag'
        verbose_name_plural = 'Skin-Tags'
        ordering = ['skin']


class Tag(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        ordering = ['name']

apps/skins/forms.py
from django import forms

from .models import Skin


class SkinForm(forms.ModelForm):
    class Meta:
        model = Skin
        fields = ['name', 'image', 'tags']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),  # 'multiple': 'multiple
        }

apps/skins/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Skin
from .forms import SkinForm

# Create your views here.
@login_required
def index(request):
    skins = Skin.objects.all()
    paginator = Paginator(skins, 4)
    page = request.GET.get('page')
    skins = paginator.get_page(page)
    skinAddform = SkinForm()
    return render(request, 'skins/index.html', {'skins': skins, 'skinAddform': skinAddform})

@login_required
def create(request):
    if request.method == 'POST':
        form = SkinForm(request.POST, request.FILES)
        if form.is_valid():
            skin = form.save(commit=False)
            skin.author = request.user.profile
            skin.likes = 1
            skin.save()
            request.user.profile.skin = skin
            request.user.profile.likes_skins.add(skin)
            request.user.profile.save()
            return redirect('skins:index')
    else:
        form = SkinForm()
    return render(request, 'skins/create.html', {'form': form})


def detail(request, id):
    skin = get_object_or_404(Skin, id=id)
    six_random_skins = Skin.objects.order_by('?')[:6]
    context = {
        'skin': skin,
        'six_random_skins': six_random_skins
    }
    
    return render(request, 'skins/detail.html', context)

@login_required
def like(request, id):
    skin = get_object_or_404(Skin, id=id)
    profile = request.user.profile
    if skin not in profile.likes_skins.all():
        profile.likes_skins.add(skin)
        skin.likes += 1
        skin.save()
    profile.skin = skin
    profile.save()
    return redirect('members:profile', id=profile.id)

apps/skins/templates/skins/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Skins page{% endblock %}

{% block content %}

    <div class="container-sm mt-4">

        <div class="row g-0 align-items-end">
            
            <div class="col text-center px-3">
              <h1 class="mb-0" style="font-size: 2.3em">
                  <a translate="no"  class="text-nowrap">{{skin.name}}</a> <small class="text-muted text-nowrap">Minecraft Skin</small>
              </h1>
            </div>
            
          </div>

          <hr class="mt-2">

          <div class="row mt-4">
            <div class="col-md-6 col-lg-7">
              <div class="card mb-3">
                <div class="card-body checkered animation-paused position-relative text-center p-0">
                  <canvas id="canvas" class="skin-3d drop-shadow auto-size align-top mx-auto" width="330" height="440" style="cursor:move;width:300px" data-id="d2434428eb6a0774" data-model="slim" data-theta="75" data-phi="22"></canvas>
                    <!-- <div class="position-absolute top-0 start-0 m-1 text-muted">
                      <h5>#8</h5>
                    </div> -->
                  <div class="position-absolute top-0 end-0 m-1">
                    <div>
                      <button style="width:36px;height:36px;" id="play-pause-btn" class="btn btn-secondary p-0 m-1" title="Play" data-play-title="Play" data-pause-title="Pause" onclick="playAnimation()"><i class="fas fa-play"></i></button>
                    </div>
                    <form action="" target="_blank" id="capture-form">
                      <button style="width:36px;height:36px;" id="render-button" class="btn btn-secondary p-0 m-1" title="Capture" onclick="capture()"><i class="fas fa-camera"></i></button>
                    </form>

                      <a style="width:36px;height:36px" href="{{skin.image.url}}" id="download-skin" class="btn btn-secondary m-1 d-flex justify-content-center align-items-center" download="{{skin.name}}.png" title="Download"><i class="fa-solid fa-download"></i></a>
                    <form method="POST" action="{% url 'skins:add_like' skin.id %}">
                      {% csrf_token %}
                      <div class="d-inline-block rounded bg-body-tertiary m-1">
                        <button style="width: 36px; height: 36px" title="Like" class="btn btn-outline-danger p-0" type="submit" name="task" value="like">
                          <i class="fas fa-heart"></i>
                        </button>
                      </div>
                    </form>
                  </div>
                  <h5 class="position-absolute bottom-0 end-0 m-1 text-muted">{{skin.likes}}<i style="vertical-align:middle;margin-left:0.1rem;font-size:67%" class="fas fa-heart"></i></h5>
                    <h5 class="position-absolute bottom-0 start-0  m-1 text-muted title-time">{{skin.created_at | timesince}}</h5>
                </div>
              </div>
                  <div class="ad-container mobile-mpu-container bg-body-tertiary d-flex d-md-none my-3">
                    <div id="nn_mobile_mpu1"></div>
                  </div>
                <div class="card mb-3" style="max-height: 15rem">
                  <div class="card-header py-1"><strong>Profiles ({{skin.liked_by.count}})</strong></div>
                  <div class="card-body player-list py-2">
                  {% for user in skin.liked_by.all %}
                    <a href="{% url 'members:profile' user.id %}" class="">{{user}}</a>
                  {% endfor %}
                     {% comment %} <a translate="no" href="/profile/Itsrealme___.1" class="">Itsrealme___</a> 
                      <a translate="no" href="/profile/JustM9owed.1" class="">JustM9owed</a>  {% endcomment %}
                      
                  </div>
                </div>
                <div class="ad-container mpu-container d-none d-md-flex mb-3">
                  <div id="nn_mpu1" data-google-query-id="CJW89dORsIQDFUUTVQgdGsMKDA" style="display: none;"><div id="google_ads_iframe_6928793,31292685/NameMC-6093bb9a4a141/NameMC-MPU1-6093bc4309518_0__container__" style="border: 0pt none; width: 250px; height: 0px;"></div></div>
                </div>
            </div>
            <div class="col-md-6 col-lg-5">
              <div class="card mb-3">
                <div class="card-body text-center py-1">
                  {% if skin.author %}
                    Автор: <a href="{% url 'members:profile' skin.author.id %}">{{skin.author}}</a>
                  {% else %}
                    Автор: Аноним
                  {% endif %}
                  
                </div>
              </div>
              <div class="card mb-3">
                <div class="card-header py-1">
                  <strong>Tags</strong>
                    <a class="float-end" href="/login?redirect=%2Fskin%2Fd2434428eb6a0774">Add / Vote (1)</a>
                </div>
                  <div class="card-body text-center py-2 text-muted">(None)</div>
              </div>
                <div class="card mb-3">
                  <div class="row g-0 p-1">
                    {% for skin in six_random_skins %}
                      <div class="col-6 col-sm-5 col-md-4 p-1">
                        <a href="{% url 'skins:detail' skin.id %}">
                          <div class="card">
                            <div class="card-body position-relative text-center checkered p-1">
                              <div>
                                <img class="drop-shadow mx-auto w-100" id="skin{{skin.id}}" style="display:none" alt="{{skin.name}}" src="" loading="lazy">
                              </div>
                              <small class="position-absolute bottom-0 end-0 text-muted mx-1">{{skin.likes}}<i style="vertical-align:middle;margin-left:0.1rem;font-size:67%" class="fas fa-heart"></i></small>
                              <small class="position-absolute bottom-0 start-0  text-muted mx-1">{{skin.created_at | timesince}}</small>
                            </div>
                          </div>
                        </a>
                      </div>
                    {% endfor %}
                  </div>
                </div>
            </div>
          </div>










          

    </div>




    <script src="{% static 'js/skinview3d.bundle.js' %}"></script>
    <script>
      const element = document.getElementById("canvas");
      console.log(element);
  
      const skinViewer = new skinview3d.SkinViewer({
            canvas: element,
            width: 330,
            height: 440,
            skin:"{{skin.image.url}}",
            enableControls: true,
        }); 
        skinViewer.animation = new skinview3d.WalkingAnimation();
        skinViewer.animation.paused = false;
        skinViewer.animation.progress = 3;
        skinViewer.animation.headBobbing = false;
            
        skinViewer.camera.rotation.x = -0.5034319968693;
        skinViewer.camera.rotation.y = -0.36908259614;
        skinViewer.camera.rotation.z = -0.196140179771;
        skinViewer.camera.position.x = -14.993128783689523;
        skinViewer.camera.position.y = 18.699720219168;
        skinViewer.camera.position.z = 33.952134734071;
        skinViewer.controls.enableZoom = false;
       

        //run 2s after the page loads
        setTimeout(() => {
          skinViewer.animation.paused = true;
        }, 10);
        

        function playAnimation() {
          skinViewer.animation.paused = !skinViewer.animation.paused;
          const btn = document.getElementById("play-pause-btn");
          if (skinViewer.animation.paused) {
            btn.innerHTML = '<i class="fas fa-play"></i>';
            btn.title = "Play";
          } else {
            btn.innerHTML = '<i class="fas fa-pause"></i>';
            btn.title = "Pause";
          }
        }

        
        function downloadBase64Image(base64String, filename) {
          // Розбиваємо base64-рядок на дві частини: тип медіа та дані
          const parts = base64String.split(';base64,');
          const mimeType = parts[0].split(':')[1];
          const imageData = atob(parts[1]);
          const bytes = new Uint8Array(imageData.length);
        
            for (let i = 0; i < imageData.length; i++) {
                bytes[i] = imageData.charCodeAt(i);
            }
        
            const blob = new Blob([bytes], { type: mimeType });
      
          if (window.navigator && window.navigator.msSaveOrOpenBlob) {
              // Для Internet Explorer
              window.navigator.msSaveOrOpenBlob(blob, filename);
          } else {
              // Створюємо посилання для завантаження файлу
              const link = document.createElement('a');
              link.href = window.URL.createObjectURL(blob);
              link.download = filename;
      
              // Додаємо посилання у DOM, клікаємо на нього та видаляємо
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
          }
      }


        function capture() {
          const img = skinViewer.canvas.toDataURL("image/png");
          console.log(img);
          downloadBase64Image(img, "skin.png");
        }


  </script>

  <script>
    const configurations = [
       {% for skin in six_random_skins %}
         {
           skin: "{{ skin.image.url }}",
           cape: null,
           id: "{{ skin.id }}",
         },
       {% endfor %}
    ];

    (async function () {
        const skinViewer = new skinview3d.SkinViewer({
            width: 200,
            height: 300,
            renderPaused: false,
        });

        skinViewer.animation = new skinview3d.WalkingAnimation();
        skinViewer.animation.paused = false;
        skinViewer.animation.progress = 3;
        skinViewer.animation.headBobbing = false;
            
        skinViewer.camera.rotation.x = -0.5034319968693;
        skinViewer.camera.rotation.y = -0.36908259614;
        skinViewer.camera.rotation.z = -0.196140179771;
        skinViewer.camera.position.x = -14.993128783689523;
        skinViewer.camera.position.y = 18.699720219168;
        skinViewer.camera.position.z = 33.952134734071;
        skinViewer.controls.enableZoom = false;
       

        //run 2s after the page loads
        setTimeout(() => {
          skinViewer.animation.paused = true;
        }, 1);
        skinViewer.zoom = 0.9;

        for (const config of configurations) {
            await Promise.all([
                skinViewer.loadSkin(config.skin),
                skinViewer.loadCape(config.cape, { backEquipment: config.backEquipment })
            ]);
            skinViewer.render();
            const image = skinViewer.canvas.toDataURL();

            img = document.getElementById("skin" + config.id);
            img.src = image;
            img.style.display = "block";
            
        }


    })();
</script>


{% endblock %}

apps/skins/templates/skins/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}Skins page{% endblock %}

{% block content %}

  <h1 class="text-3xl text-center font-bold mt-3">
    Skins
</h1>
  <!-- <a href="{% url 'skins:create' %}" class="btn btn-outline-primary">Add skin</a> -->
  <!-- <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addSkin">Add skin</a> -->
  <div class="row mt-3 justify-content-center gy-5">
    {% for skin in skins %}
    <div class="col-4 col-md-2">
      <a href="{% url 'skins:detail' skin.id %}">
        <div class="card">
          <div class="card-header text-center p-2 text-white">
            <p class="p-0 m-0">{{ skin.name }}</p>
          </div> 
          <div class="checkered">
            <img id="skin{{ skin.id }}" src="" class="card-img-top">
          </div>
        </div>
      </a>
  </div>
  {% endfor %}
  </div>
 
  <!-- paginator django -->
  <div class="d-flex justify-content-center mt-3">
    {% if skins.has_other_pages %}
    <ul class="pagination pagination-lg">
      {% if skins.has_previous %}
      {% if skins.number|add:'-2' > 0 %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="First">
            <span aria-hidden="true">1</span>
          </a>
        </li>
      {% endif %}
        <li class="page-item">
          <a class="page-link" href="?page={{ skins.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">{{ skins.previous_page_number }}</span>
          </a>
        </li>
      {% endif %}
      
        
      <li class="page-item active" aria-current="page">
        <span class="page-link">{{ skins.number }}</span>
      </li>

      {% if skins.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ skins.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">{{ skins.next_page_number }}</span>
        </a>
      </li>
      {% if skins.number|add:'2' < skins.paginator.num_pages %}
      <li class="page-item">
        <a class="page-link" href="?page={{ skins.paginator.num_pages }}" aria-label="Last">
          <span aria-hidden="true">{{ skins.paginator.num_pages }}</span>
        </a>
      </li>
      {% endif %}
      {% endif %}
    </ul>
    {% endif %}
  </div>




<!-- Modal -->
<div class="modal fade" id="addSkin" tabindex="-1" aria-labelledby="addSkinLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addSkinLabel">Add Skin</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">❌</button>
      </div>
      <div class="modal-body">
        <form action="{% url 'skins:create' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name">
          </div>
          <div class="mb-3">
            <label for="image" class="form-label">Image</label>
            <input type="file" class="form-control" id="image" name="image">
          </div>
          <button type="submit" class="btn btn-primary">Add</button>

      </div>
    </div>
  </div>
</div>


  <!-- <canvas id="canvas" width="200" height="200"></canvas>
  <button id="showdata">Show data</button> -->
  <script src="{% static 'js/skinview3d.bundle.js' %}"></script>
  <script>
    const configurations = [
       {% for skin in skins %}
         {
           skin: "{{ skin.image.url }}",
           cape: null,
           id: "{{ skin.id }}",
         },
       {% endfor %}
    ];
     //const element = document.getElementById("canvas");

    //const skinViewer1 = new skinview3d.SkinViewer({
    //  canvas: element,
     //   width: 200,
//height: 200,
    //    skin: configurations[1].skin,
    //    enableControls: true,
//}); 
    //document.getElementById("showdata").addEventListener("click", () => {
    //  console.log(skinViewer1);
    //});

    (async function () {
        const skinViewer = new skinview3d.SkinViewer({
            width: 200,
            height: 300,
            renderPaused: false,
        });

        skinViewer.animation = new skinview3d.WalkingAnimation();
        skinViewer.animation.paused = false;
        skinViewer.animation.progress = 3;
        skinViewer.animation.headBobbing = false;
            
        skinViewer.camera.rotation.x = -0.5034319968693;
        skinViewer.camera.rotation.y = -0.36908259614;
        skinViewer.camera.rotation.z = -0.196140179771;
        skinViewer.camera.position.x = -14.993128783689523;
        skinViewer.camera.position.y = 18.699720219168;
        skinViewer.camera.position.z = 33.952134734071;
        skinViewer.controls.enableZoom = false;
       

        //run 2s after the page loads
        setTimeout(() => {
          skinViewer.animation.paused = true;
        }, 10);
        skinViewer.zoom = 0.9;

        for (const config of configurations) {
            await Promise.all([
                skinViewer.loadSkin(config.skin),
                skinViewer.loadCape(config.cape, { backEquipment: config.backEquipment })
            ]);
            skinViewer.render();
            const image = skinViewer.canvas.toDataURL();

            document.getElementById("skin" + config.id).src = image;
        }


    })();
</script>
{% endblock %}