apps/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
   path('' , views.index , name='index'),
]

apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
   path('' , views.index , name='index'),
   path('contact_form/' , views.contact_form , name='question')
]

coremine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('skins/', include('apps.skins.urls')),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/forms.py
from django import forms

class ContactForm(forms.Form):
    COURSES = [
        ('minecraft', 'Minecraft'),
        ('python', 'Python'),
        ('scratch', 'Scratch'),
        ('html', 'HTML'),
        ('unity', 'Unity'),
    ]
    
    subject = forms.CharField(max_length=100, label='Тема листа')
    email = forms.EmailField(required=False, label='Ваша електронна адреса')
    course = forms.ChoiceField(choices=COURSES, label='Курс')
    message = forms.CharField(widget=forms.Textarea, label='Текст листа')

apps/main/views.py
from django.core.mail import send_mail

from django.shortcuts import render
#messages
from django.contrib import messages

from .forms import ContactForm

# Create your views here.
def index(request):
    contact_form = ContactForm()
    context = {
        'contact_form': contact_form,
    }
    return render(request, 'core/index.html', context)


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            course = form.cleaned_data['course']
            message = form.cleaned_data['message']
            
            text = f'Ви вибрали курс: {course}\n\n{message}\\n\nВаша електронна адреса: {email}'
            
            send_mail(subject, text, 'noreply@robosmart.pp.ua', [f'{email}'])
            messages.success(request, 'Лист відправлено')
            return render(request, 'core/index.html')
        else:
            messages.error(request, 'Помилка відправлення листа')
    else:
        form = ContactForm()
    return render(request, 'core/index.html', {'form': form})

apps/main/templates/core/index.html
{% extends "base.html" %}

{% load static %}


{% block title %}Main page{% endblock %}

{% block content %}
<div class="mt-4 p-4 bg-body-tertiary rounded-lg">
  <h1 class="text-3xl text-center font-bold">
    Main page
  </h1>
  <p class="text-center">Welcome to the main page of the site</p>
</div>
<div class="mt-4 p-4 bg-body-tertiary rounded-lg">
  <h2 class="text-2xl font-bold">Features</h2>
  <p>Here are some of the features of the site:</p>
  <ul>
    <li>Registration and authorization</li>
    <li>Profile editing</li>
    <li>Creating and editing posts</li>
    <li>Comments</li>
  </ul>
</div>

<div class="mt-4 p-4 bg-body-tertiary rounded-lg">
  <h2 class="text-2xl font-bold">Qustions</h2>
  <form action="{% url 'main:question' %}" method="post">
    {% csrf_token %}
    {{ contact_form.as_p }}
    <button type="submit" class="btn btn-primary">Send</button>
  </form>
</div>

{% endblock %}